- name: create directory
  file:
    path: "{{ scheduler_install_path }}/{{ item }}"
    state: directory
  with_items:      
    - 'bin'
    - 'cert'
    - 'data'
    - 'log'

- name: upload config
  notify: update supervisord
  template: 
    src: "{{ item }}.j2"
    dest: "{{ scheduler_install_path }}/{{ item }}"
  with_items:      
    - "scheduler.ini"

- name: upload config
  notify: restart scheduler
  template: 
    src: kubeconfig.yml.j2
    dest: "{{ scheduler_install_path }}/kubeconfig.yml"

- name: upload scheduler
  notify: restart scheduler
  copy: 
    src: "{{ item }}"
    dest: "{{ scheduler_install_path }}/bin/"
    mode: u=rwx
  with_items:
    - "{{ build_path }}/build-kubernetes/kubernetes/_output/local/bin/linux/amd64/kube-scheduler"

- name: upload certs ca
  notify: restart scheduler
  copy:
    src: "{{ item }}"
    dest: "{{ scheduler_install_path }}/cert/ca/"
  with_items:
    - "{{ ca_path }}/ca.pem"

- name: upload serviceAccount ca
  notify: restart scheduler
  copy:
    src: "{{ item }}"
    dest: "{{ scheduler_install_path }}/cert/service_account/"
  with_items:
    - "{{ serviceAccount_path }}/ca.pem"
    - "{{ serviceAccount_path }}/key.pem"

- name: upload apiserver client certs 
  notify: restart scheduler
  copy:
    src: "{{ item }}"
    dest: "{{ scheduler_install_path }}/cert/apiserver-client/"
  with_items:
    - "{{ apiserver_client_certs_scheduler }}/{{ inventory_hostname }}/cert.pem"
    - "{{ apiserver_client_certs_scheduler }}/{{ inventory_hostname }}/key.pem"

- name: upload scripts
  copy:
    src: "{{ item }}"
    dest: "{{ scheduler_install_path }}/"
    mode: u=rwx
  with_items:
    - start.sh
    - stop.sh

- name: create link
  notify: update supervisord
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: "{{ scheduler_install_path }}/scheduler.ini", dest: "/etc/supervisord.d/scheduler.ini" }
